--
-- SQL schema for the AI YouTube Manager.
--
-- Run this file in the Supabase SQL editor to create the required tables
-- and policies.  Supabase uses PostgreSQL under the hood, so all SQL
-- features supported by PostgreSQL can be used here.

-- Enable the pgcrypto extension for generating UUIDs.
create extension if not exists pgcrypto;

-- Users are managed by Supabase auth.  Each row in this table is
-- automatically inserted/updated by Supabase when a new user signs up.
-- Additional profile information can be stored in this table.
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  display_name text,
  created_at timestamp with time zone default now()
);

-- Connected YouTube channels.  A user can connect multiple channels if
-- desired, but typically there will be one channel per user.
create table if not exists channels (
  id uuid default gen_random_uuid() primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  yt_channel_id text not null,
  title text,
  refresh_token text, -- encrypted refresh token (use vault or encryption functions)
  connected_at timestamp with time zone default now()
);

-- Videos synced from YouTube.  These records are populated by the
-- background sync job which fetches the user's recent uploads.
create table if not exists videos (
  id uuid default gen_random_uuid() primary key,
  channel_id uuid not null references channels(id) on delete cascade,
  yt_video_id text not null,
  title text,
  description text,
  published_at timestamp with time zone,
  duration integer, -- in seconds
  thumbnail_url text,
  created_at timestamp with time zone default now()
);

-- Daily metrics for each video.  You can join this table with the
-- `videos` table to build charts over time.  The sync job should
-- upsert rows here with the latest values.
create table if not exists video_metrics_daily (
  video_id uuid not null references videos(id) on delete cascade,
  date date not null,
  views bigint default 0,
  watch_time numeric default 0,
  average_view_duration numeric default 0,
  impressions bigint default 0,
  click_through_rate numeric default 0,
  subscribers_gained integer default 0,
  primary key (video_id, date)
);

-- Content ideas generated by AI.  Each idea has a score and a reason.
create table if not exists content_ideas (
  id uuid default gen_random_uuid() primary key,
  channel_id uuid not null references channels(id) on delete cascade,
  idea text not null,
  score numeric default 0,
  reason text,
  format text default 'long', -- long, short, community
  created_at timestamp with time zone default now()
);

-- AI outputs such as generated titles, hooks, descriptions and tags.
create table if not exists ai_outputs (
  id uuid default gen_random_uuid() primary key,
  idea_id uuid references content_ideas(id) on delete cascade,
  title text,
  hook text,
  description text,
  tags text[],
  created_at timestamp with time zone default now()
);

-- Tasks that the AI assistant assigns to the user.  These can be
-- weekly tasks or one‑off suggestions.
create table if not exists tasks (
  id uuid default gen_random_uuid() primary key,
  channel_id uuid not null references channels(id) on delete cascade,
  description text not null,
  completed boolean default false,
  due_date date,
  created_at timestamp with time zone default now()
);

-- Scheduled uploads created by the user.  The upload manager writes
-- entries into this table.  A background job should watch for rows
-- where `publish_at` is in the past and then call the YouTube API to
-- upload and schedule the video.  Once the upload is complete, the
-- job can either delete the row or mark it as processed.
create table if not exists scheduled_uploads (
  id uuid default gen_random_uuid() primary key,
  channel_id uuid not null references channels(id) on delete cascade,
  title text not null,
  description text,
  tags text[],
  video_path text not null, -- path to the uploaded file stored in Supabase storage or another bucket
  publish_at timestamp with time zone not null,
  processed boolean default false,
  created_at timestamp with time zone default now()
);

-- Row level security (RLS)
alter table profiles enable row level security;
alter table channels enable row level security;
alter table videos enable row level security;
alter table video_metrics_daily enable row level security;
alter table content_ideas enable row level security;
alter table ai_outputs enable row level security;
alter table tasks enable row level security;
alter table scheduled_uploads enable row level security;

-- Policies granting access only to the owner of each row.  Supabase
-- provides the `auth.uid()` function which returns the id of the
-- currently authenticated user.
create policy "Allow users to access their own profiles" on profiles
  for select using (id = auth.uid());

create policy "Allow users to manage their own channels" on channels
  for all using (user_id = auth.uid());

create policy "Allow users to manage their own videos" on videos
  for all using (
    exists (select 1 from channels c where c.id = videos.channel_id and c.user_id = auth.uid())
  );

create policy "Allow users to access their own video metrics" on video_metrics_daily
  for all using (
    exists (
      select 1 from videos v
      join channels c on v.channel_id = c.id
      where v.id = video_metrics_daily.video_id
        and c.user_id = auth.uid()
    )
  );

create policy "Allow users to manage their own ideas" on content_ideas
  for all using (
    exists (
      select 1 from channels c where c.id = content_ideas.channel_id and c.user_id = auth.uid()
    )
  );

create policy "Allow users to manage their own AI outputs" on ai_outputs
  for all using (
    exists (
      select 1 from content_ideas ci
      join channels c on ci.channel_id = c.id
      where ci.id = ai_outputs.idea_id and c.user_id = auth.uid()
    )
  );

create policy "Allow users to manage their own tasks" on tasks
  for all using (
    exists (
      select 1 from channels c where c.id = tasks.channel_id and c.user_id = auth.uid()
    )
  );

create policy "Allow users to manage their own scheduled uploads" on scheduled_uploads
  for all using (
    exists (
      select 1 from channels c where c.id = scheduled_uploads.channel_id and c.user_id = auth.uid()
    )
  );